/* tslint:disable */
/* eslint-disable */
/**
 * pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineResponse500
 */
export interface InlineResponse500 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse500
     */
    'message'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineResponse500
     */
    'stack'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse500
     */
    'type'?: string;
}

