/* tslint:disable */
/* eslint-disable */
/**
 * pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoginRes
 */
export interface LoginRes {
  /**
   *
   * @type {boolean}
   * @memberof LoginRes
   */
  error?: boolean;
  /**
   *
   * @type {string}
   * @memberof LoginRes
   */
  msg?: string;
  /**
   *
   * @type {string}
   * @memberof LoginRes
   */
  idToken?: string;
}
