/* tslint:disable */
/* eslint-disable */
/**
 * pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface LoginVm
 */
export interface LoginVm {
    /**
     *
     * @type {string}
     * @memberof LoginVm
     */
    'username'?: string;
    /**
     *
     * @type {string}
     * @memberof LoginVm
     */
    'password'?: string;
}

/**
 *
 * @export
 * @interface SecretLoginVM
 */
export interface SecretLoginVM {
    /**
     *
     * @type {string}
     * @memberof SecretLoginVM
     */
    'key'?: string;
}

