/* tslint:disable */
/* eslint-disable */
/**
 * pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PageableObject } from "./pageable-object";
// May contain unused imports in some cases
// @ts-ignore
import { SecretKey } from "./secret-key";
// May contain unused imports in some cases
// @ts-ignore
import { SortObject } from "./sort-object";

/**
 *
 * @export
 * @interface PageSecretKey
 */
export interface PageSecretKey {
  /**
   *
   * @type {number}
   * @memberof PageSecretKey
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof PageSecretKey
   */
  totalElements?: number;
  /**
   *
   * @type {number}
   * @memberof PageSecretKey
   */
  size?: number;
  /**
   *
   * @type {Array<SecretKey>}
   * @memberof PageSecretKey
   */
  content?: Array<SecretKey>;
  /**
   *
   * @type {number}
   * @memberof PageSecretKey
   */
  number?: number;
  /**
   *
   * @type {SortObject}
   * @memberof PageSecretKey
   */
  sort?: SortObject;
  /**
   *
   * @type {PageableObject}
   * @memberof PageSecretKey
   */
  pageable?: PageableObject;
  /**
   *
   * @type {boolean}
   * @memberof PageSecretKey
   */
  first?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof PageSecretKey
   */
  last?: boolean;
  /**
   *
   * @type {number}
   * @memberof PageSecretKey
   */
  numberOfElements?: number;
  /**
   *
   * @type {boolean}
   * @memberof PageSecretKey
   */
  empty?: boolean;
}
