/* tslint:disable */
/* eslint-disable */
/**
 * pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserInfo } from './user-info';

/**
 * 
 * @export
 * @interface PayInfo
 */
export interface PayInfo {
    /**
     * 
     * @type {number}
     * @memberof PayInfo
     */
    'id'?: number;
    /**
     * 
     * @type {UserInfo}
     * @memberof PayInfo
     */
    'payingUser'?: UserInfo;
    /**
     * 
     * @type {UserInfo}
     * @memberof PayInfo
     */
    'receivingUser'?: UserInfo;
    /**
     * 
     * @type {string}
     * @memberof PayInfo
     */
    'state'?: PayInfoStateEnum;
    /**
     * 
     * @type {number}
     * @memberof PayInfo
     */
    'money'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayInfo
     */
    'create'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayInfo
     */
    'finish'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayInfo
     */
    'goodsInfo'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayInfo
     */
    'goodsType'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayInfo
     */
    'remarks'?: string;
}

export const PayInfoStateEnum = {
    Unpaid: 'Unpaid',
    Paid: 'Paid',
    Canceled: 'Canceled',
    Refunded: 'Refunded'
} as const;

export type PayInfoStateEnum = typeof PayInfoStateEnum[keyof typeof PayInfoStateEnum];


