/* tslint:disable */
/* eslint-disable */
/**
 * pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PayVm
 */
export interface PayVm {
    /**
     * 
     * @type {string}
     * @memberof PayVm
     */
    'userId'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayVm
     */
    'money'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayVm
     */
    'create'?: string;
}

