/* tslint:disable */
/* eslint-disable */
/**
 * pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RequestReq
 */
export interface RequestReq {
    /**
     * 
     * @type {string}
     * @memberof RequestReq
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof RequestReq
     */
    'idCard': string;
    /**
     * 
     * @type {string}
     * @memberof RequestReq
     */
    'remarks'?: string;
}

