/* tslint:disable */
/* eslint-disable */
/**
 * pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserInfo } from './user-info';

/**
 * 
 * @export
 * @interface RoleRequest
 */
export interface RoleRequest {
    /**
     * 
     * @type {number}
     * @memberof RoleRequest
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RoleRequest
     */
    'create'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRequest
     */
    'finish'?: string;
    /**
     * 
     * @type {UserInfo}
     * @memberof RoleRequest
     */
    'applicant'?: UserInfo;
    /**
     * 
     * @type {string}
     * @memberof RoleRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRequest
     */
    'idCard'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRequest
     */
    'remarks'?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleRequest
     */
    'to'?: RoleRequestToEnum;
    /**
     * 
     * @type {UserInfo}
     * @memberof RoleRequest
     */
    'approver'?: UserInfo;
    /**
     * 
     * @type {string}
     * @memberof RoleRequest
     */
    'state'?: RoleRequestStateEnum;
}

export const RoleRequestToEnum = {
    Personal: 'Personal',
    Business: 'Business',
    Admin: 'Admin'
} as const;

export type RoleRequestToEnum = typeof RoleRequestToEnum[keyof typeof RoleRequestToEnum];
export const RoleRequestStateEnum = {
    Unprocessed: 'Unprocessed',
    Permit: 'Permit',
    Reject: 'Reject',
    CanReapply: 'CanReapply'
} as const;

export type RoleRequestStateEnum = typeof RoleRequestStateEnum[keyof typeof RoleRequestStateEnum];


