/* tslint:disable */
/* eslint-disable */
/**
 * pay
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TradingCode
 */
export interface TradingCode {
  /**
   *
   * @type {string}
   * @memberof TradingCode
   */
  id?: string;
  /**
   *
   * @type {number}
   * @memberof TradingCode
   */
  userInfoId?: number;
  /**
   *
   * @type {string}
   * @memberof TradingCode
   */
  tradingType?: TradingCodeTradingTypeEnum;
  /**
   *
   * @type {number}
   * @memberof TradingCode
   */
  money?: number;
  /**
   *
   * @type {string}
   * @memberof TradingCode
   */
  create?: string;
  /**
   *
   * @type {string}
   * @memberof TradingCode
   */
  state: TradingCodeStateEnum;
  /**
   *
   * @type {number}
   * @memberof TradingCode
   */
  payId?: number;
}

export const TradingCodeTradingTypeEnum = {
  Receipt: "Receipt",
  Payment: "Payment",
} as const;

export type TradingCodeTradingTypeEnum =
  (typeof TradingCodeTradingTypeEnum)[keyof typeof TradingCodeTradingTypeEnum];
export const TradingCodeStateEnum = {
  NotNotified: "NotNotified",
  Created: "Created",
  Finished: "Finished",
  Canceled: "Canceled",
} as const;

export type TradingCodeStateEnum =
  (typeof TradingCodeStateEnum)[keyof typeof TradingCodeStateEnum];
